version: '3'

services:
#  locust-master:
#    image: locustio/locust
#    volumes:
#      - ./scripts:/scripts
#    ports:
#      - "8089:8089"
#    command: -f /scripts/locustfile.py --master
#    environment:
#      LOCUST_MODE: master
#
#  locust-worker:
#    image: locustio/locust
#    command: -f /scripts/locustfile.py --worker
#    volumes:
#      - ./scripts:/scripts
#    depends_on: [ locust-master ]
#    environment:
#      LOCUST_MODE: worker
#      LOCUST_MASTER_HOST: locust-master

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - "54322:5432"
    networks:
      - db
  django:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/app
    ports:
    - "8200:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    networks:
      proxynetwork:
        aliases:
            - main
      db:
      app:


networks:
  proxynetwork:
    external: true
  db: {}
  app: {}
