# Generated by Django 3.1.5 on 2021-04-02 06:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210402_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mark_point',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
