# Generated by Django 3.1.5 on 2021-03-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210320_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
